package com.sklad.skladproject.dto

// Item that is purchased from some stock to be redistributed later within shops
data class PurchaseItemDto(
    // Unique describing string (= id) generated by frontend to differ purchase items in a list of purchases
    // This id not used anywhere else
    val describingString: String,
    // Date of the purchase operation
    val date: String,

    // Name of the item
    val name: String,
    // Quantity of the item
    val quantity: Double,
    // Quantity measure unit
    val quantityUnit: String,

    // Name of the package where this item is placed
    val packName: String?,
    // Weight of the package
    val packWeight: Double?,
    // Package measure unit
    val packUnit: String,

    // Bought price of the item
    val boughtPrice: Double,
    // Measure unit of the bought price (currency, for example)
    val boughtPriceUnit: String,

    // State of this purchase item (for example, "added", "stored" or "canceled")
    // Could be null, if purchase operation item is added
    val state: String?,
    // Timestamp of the last state change
    // Could be null, if purchase operation item is added
    val lastStateChangedTimestamp: Long?
)
