INSERT INTO UNIT (unit_name) VALUES ('kg') ON CONFLICT DO NOTHING;

INSERT INTO UNIT (unit_name) VALUES ('g') ON CONFLICT DO NOTHING;

INSERT INTO UNIT (unit_name) VALUES ('l') ON CONFLICT DO NOTHING;

INSERT INTO UNIT (unit_name) VALUES ('rub') ON CONFLICT DO NOTHING;

INSERT INTO UNIT (unit_name) VALUES ('amount') ON CONFLICT DO NOTHING;